export const USERTODO_DATA = "USERTODO_DATA";

export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_ERROR = "GET_TODO_ERROR";

export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_ERROR = "ADD_TODO_ERROR";

export const UPDATE_TODO_STATUS_SUCCESS = "UPDATE_TODO_STATUS_SUCCESS";
export const UPDATE_TODO_STATUS_ERROR = "UPDATE_TODO_STATUS_ERROR";

export const GET_BOARD_NAME_SUCCESS = "GET_BOARD_NAME_SUCCESS";
export const GET_BOARD_NAME_ERROR = "GET_BOARD_NAME_ERROR";

export const ADD_BOARD_NAME_SUCCESS = "ADD_BOARD_NAME_SUCCESS";
export const ADD_BOARD_NAME_ERROR = "ADD_BOARD_NAME_ERROR";

export const GET_TODO_USING_BOARD_ID_SUCCESS =
  "GET_TODO_USING_BOARD_ID_SUCCESS";
export const GET_TODO_USING_BOARD_ID_ERROR = "GET_TODO_USING_BOARD_ID_ERROR";

export const GET_ALL_TASKS_SUCCESS = "GET_ALL_TASKS_SUCCESS";
export const GET_ALL_TASKS_ERROR = "GET_ALL_TASKS_ERROR";